services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      # Add legacy watch mode for nodemon
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - pharma-network
    # Add legacy watch flag to nodemon
    command: npm run dev -- --legacy-watch
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      # Add polling for Next.js
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - pharma-network
    depends_on:
      - backend

networks:
  pharma-network:
    driver: bridge